<div class="content">
    <h2>О Нас</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, 
        sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
        Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea 
        commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat 
        nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id e
        st laborum.</p>

    <div>
        <h2 class = 'title-porto'>Портфолио</h2>
        <table>
            <tr><td><h5>Год</h5></td><td><h5>Проект</h5></td><td><h5>Описание</h5></td></tr>
            <?php
                require_once MODEL . 'Model.php';
            ?>
        </table>
    </div>
</div>
