<div class="container pt-4">

    <h1 class="mb-4"><a href="/">Image gallery</a></h1>

    <!-- Outputting success/error messages -->
    <?php foreach ($errors as $error): ?>
        <div class="alert alert-danger"><?php echo $error; ?></div>
    <?php endforeach; ?>

    <?php foreach ($messages as $message): ?>
        <div class="alert alert-success"><?php echo $message; ?></div>
    <?php endforeach; ?>

    <h2 class="mb-4">File<?php echo $imageFileName; ?></h2>

    <div class="row">
        <div class="col-12 col-sm-8 offset-sm-2">

            <img src="<?php echo UPLOAD_DIR . DIRECTORY_SEPARATOR . $imageFileName ?>" class="img-thumbnail mb-4"
                 alt="<?php echo $imageFileName ?>">

            <h3>Comments</h3>
            <?php if (!empty($comments)): ?>
                <?php foreach ($comments as $key => $comment): ?>
                    <p class="<?php echo (($key % 2) > 0) ? 'bg-light' : ''; ?>"><?php echo $comment; ?></p>
                <?php endforeach; ?>
            <?php else: ?>
                <p class="text-muted">No comments yet, be the first!</p>
            <?php endif; ?>

            <!-- Форма добавления комментария -->
            <form method="post" action="coments">
                <div class="form-group">
                    <label for="comment">your comment</label>
                    <textarea class="form-control" id="comment" name="comment" rows="3" required></textarea>
                </div>
                <hr>
                <button type="submit" class="btn btn-primary">Send</button>
            </form>
        </div>
    </div><!-- /.row -->
</div><!-- /.container -->

