<div class="content content-cont"> 
    <h3>Обратная связь</h3> 
    <div class = 'form-box'>
        <form method="post">
            <p>Ваше Имя и Фамилия : 
                <input class = 'name' type="text" name="name" />
            </p>
            <p>Ваш email: 
                <input class = 'email' type="email" name="email" />
            </p>
            <p>Ваше Сообщение : 
            <textarea class = 'notice' name="comment" placeholder="Enter text here..."></textarea>
            </p>
            <input type="submit">
        </form>
        <div class = 'output-box'>
        <?php include_once VIEW . "inviews" . DIRECTORY_SEPARATOR . "sendstatus.phtml";?>
        </div>
    </div>
</div>