<!-- login form -->
<div onclick="showlogin('none')" id="gray"></div>
<div id="window">
    <!-- Picture cross -->
    <img class="closd" src="app\img\close.png" alt="" onclick="showlogin('none')">
    <div class="form">
        <h4>login</h4>
        <form id="login">
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" class="form-control" id="email" name="useremail" aria-describedby="emailHelp"
                       placeholder="Enter your email">
                <div class="form-control-feedback"></div>
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" name="userpassword" placeholder="Password">
                <div class="form-control-feedback"></div>
            </div>

            <button type="submit" class="btn btn-primary">Login</button>
        </form>
    </div>
    <p class="regformtext">If you are not yet registered, follow the link to register</p>
    <button onclick="showreg('block')" class="btn btn-link ">Registration</button>
</div>

<!-- Registration Form -->

<div onclick="showreg('none')" id="grayreg"></div>
<div id="windowreg">
    <!-- Picture cross -->
    <img class="closd" src="app\img\close.png" alt="" onclick="showreg('none')">
    <div class="form">
        <h4>Registration</h4>
        <form id="registration">
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" class="form-control" id="email" name="useremail" aria-describedby="emailHelp"
                       placeholder="Enter your email">
                <div class="form-control-feedback"></div>
            </div>
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class="form-control" id="name" name="username" aria-describedby="emailHelp"
                       placeholder="Enter your name">
                <div class="form-control-feedback"></div>
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" name="userpassword" placeholder="Password">
                <div class="form-control-feedback"></div>
            </div>
            <div class="form-group">
                <label for="repeat-password">Repeat Password</label>
                <input type="password" class="form-control" id="repeat-password" name="repeat-password"
                       placeholder="Repeat password">
                <div class="form-control-feedback"></div>
            </div>
            <button type="submit" class="btn btn-primary">Registration</button>
        </form>
    </div>
</div>

